Grep Command
akhvorov/software-design-course pull request #2
Opened 2019-03-04 00:15 UTC by akhvorov

2019-03-04 00:48 UTC, akhvorov commented
О выборе инструмента парсинга аргументов. Были рассмотрены библиотеки args4j, JCommander, Commons CLI и picocli, так как их чаще всего рекомендовали для разбора аргументов на stackoverflow. Начал смотреть с JCommander. Документация была понятна, но вписав в gradle зависимость, получилась какая-то ошибка, я немного потыкался в это, но потом решил, что дольше буду разбираться с её устранением, чем найду другой вариант. Сайт Commons CLI был не так понятен, так как строчки, которую нужно было вписать в gradle я не нашел быстро, да и документацию тоже надо было еще найти на сайте, поэтому этот вариант тоже не обрадовал, хотя принадлежность к apache и внушало доверие. args4j понравилась хорошими отзывами и MIT лицензией, но сайт показался не очень красивым (видимо, устаревший дизайн заставил думать, что библиотека такая же), а установка вела на maven. Возможно эта проблема бы решилась, но имелись и аналоги, я продолжил поиски. picocli имеет хороший сайт, где документация и базовые вещи показывают на первой же странице, полистав совсем немного, сложилось хорошее впечатление. Строка для добавления в gradle нашлась тоже быстро и с ней все заработало. Также проект довольно популярный, что также в плюс ему.

2019-03-30 20:57 UTC, ottergottaott requested changes
Работа в целом очень хорошая.
Есть несколько замечаний по функциональности
- вызов внешних команд поддержан, но при вызове команды с аргументами ругается `"Can't execute external command"`
- на некотором вводе лепит много `$`
```
x=ec
y=ho
$x$y 10
$ $ $ $ 10
```
это не критично, но думаю, что потенциальному пользователю было бы не очень приятно такое видеть:)

Пока что не проверял grep, по нему оставлю комментарии позже.

> но сайт показался не очень красивым (видимо, устаревший дизайн заставил думать, что библиотека такая же), а установка вела на maven

маленький лайфхак: на [maven repository](https://mvnrepository.com/artifact/args4j/args4j/2.33) обычно есть вкладка `gradle`
в твоем случае там написано 
```groovy
// https://mvnrepository.com/artifact/args4j/args4j
compile group: 'args4j', name: 'args4j', version: '2.33'
```

2019-03-30 20:57 UTC, aleksZubakov commented on src/test/java/ru/ifmo/sdc/cli/ShellTest.java
> +    public void testEcho() throws IOException {
Большой плюсик за хорошее покрытие тестами, но было бы хорошо добавить именно unit-тесты, отдельно тестирующие конкретные компоненты программы.
Например, отдельно `wc`  без запуска парсинга, отдельно парсер и т.д.

2019-03-30 20:57 UTC, aleksZubakov commented on src/main/java/ru/ifmo/sdc/cli/commands/ExternalCommand.java
> +            child = Runtime.getRuntime().exec(commandName + String.join(" ", args));
Выражению `commandName + String.join(" ", args)`  не хватает пробела посерединке :)

2019-03-30 20:57 UTC, aleksZubakov commented on src/main/java/ru/ifmo/sdc/cli/Parser.java
> +    private static List<List<String>> groupByCommand(final List<String> tokens) {
Этот метод все-таки скорее `splitByPipe`, чем `groupByCommand`
Плюс, если все-таки это `groupByCommand`, методу не хватает более детального описания каким образом и что он группирует.

2019-03-30 20:57 UTC, aleksZubakov commented on src/main/java/ru/ifmo/sdc/cli/Parser.java
> +        boolean lastTokenIsQuoted = false;
Код хорошо написано, но на мой взгляд этот метод  сильно нагруженный с точки зрения выполняемой логики в нем, я бы попробовал разбить этот код на методы, мб, вынес бы отдельный класс, в котором будет `state` и сопутствующие вещи

Плюс вот эти переменные 
```
final int ordinary = 0;
final int inWeakQuote = 1;
final int inStrongQuote = 2;
```
можно было бы вынести из метода, они сильно похожи на константы.  Мб, даже радикально, создав для них заприваченный enum

2019-03-30 20:57 UTC, aleksZubakov commented on src/main/java/ru/ifmo/sdc/cli/commands/Command.java
> +    protected String commandName = null;
_Не обязательное к исправлению_
На мой взгляд лучше не совмещать команды, которые в дальнейшем будут выполняться, с `@Parameters` из picocli и вот почему:
Если бы ты вынес отдельные классы, предназаненные для парсинга аргументов, а из них бы создавал `Command`, то кода бы появилось не сильно больше, а команды при этом могли бы держать `final` поля, что может уберечь от чьих-то кривых рук или дать хороший бонус в виде thread-safety класса([на sof](https://stackoverflow.com/questions/7144915/final-fields-and-thread-safety) можно почитать подробнее).

Да и в целом кажется разумным разделить логику по парсингу и логику по исполнению.

2019-03-30 20:57 UTC, aleksZubakov commented on src/main/java/ru/ifmo/sdc/cli/Environment.java
> +    public String substitute(final String line) {
Кажется, `Environment` берет на себя две ответственности: 
- хранит переменные и предоставляет интерфейс для их изменения
- инкапсулирует логику по подстановке
думаю, это можно было бы разделить(или объяснить почему лучше оставить так)

2019-04-06 15:47 UTC, ottergottaott requested changes
Замечания по grep:
- Вне зависимости от результата работы и переданных ключей всегда выводит первую строку файла
-  при попытке ввести `grep -A` или `grep -A text text test.txt` завершает работу `shell` с ошибкой, хотелось бы, чтобы вместо этого мягко сообщалось пользователю, что он не прав, и работа продолжалась
-  не распозанет ошибку в такой команде `grep -A -1 text test.txt` и выводит первую строку файла, хотя `-1` не является валидным аргументом, о чем стоит сообщать
- не нашел тесты, покрывающие отдельно `grep`

В остальном все ок

2019-04-07 14:34 UTC, akhvorov commented
Спасибо. Вроде все поправил, кроме
> на некотором вводе лепит много $

потому что у меня не воспроизводиться. 
Тут и CLI и Grep.

2019-04-13 16:20 UTC, aleksZubakov commented
Меня все устраивает, @yurii-litvinov, думаю, что можно засчитавать CLi/grep

2019-04-18 17:28 UTC, yurii-litvinov requested changes
Перенаправление потока ошибок из внешних программ не работает. Пишем `git ololo`, ничего не происходит. А должно показывать ругань от гита.

Ещё `cat build.gradle | grep plugin` ничего не выводит, тогда как `grep plugin build.gradle` нормально работает.

Ещё неплохо было бы прикрутить CI.

grep действительно можно зачесть, а CLI давайте надо будет поправить

2019-04-18 17:28 UTC, yurii-litvinov commented on src/main/java/ru/ifmo/sdc/cli/Parser.java
> +        final StringBuilder sb = new StringBuilder();
В современной Java наконец появились var-ы, чтобы два раза тип не писать

2019-05-12 16:39 UTC, akhvorov commented
Вывод ошибки сторонних вызовов добавил. Вторая проблема у меня не воспроизводится, работает нормально и одинаково в обоих случаях. CI добавил.

2019-05-15 16:37 UTC, akhvorov commented
@aleksZubakov @yurii-litvinov

2019-05-26 14:07 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2019-06-10 18:29 UTC, merged