Defects
akhvorov/software-design-course pull request #4
Opened 2019-03-09 15:39 UTC by akhvorov

2019-06-01 14:50 UTC, yurii-litvinov requested changes
- Загруженность конвейера внутреннее дело завода, вряд ли она может считаться внешним управлением. Лучше её вообще не контекстной диаграмме не рисовать
- План вряд ли материал для процесса сборки, это скорее управление
- И я бы ещё процесс ремонта как-то отобразил, мы ведь в конечном итоге планируем разрабатывать приложения для учёта дефектов, так что хотим понимать место нашего приложения в общем бизнес-процессе
- BPMN диаграмма яростно не соответствует синтаксису BPMN. Это скорее неаккуратно нарисованный workflow, который можно было бы показать начальству на митинге, но только если не требуется проявлять профессионализм в аналитике :) Хочется именно формальную BPMN-диаграмму. Рекомендую набор "каноничных" примеров диаграмм бизнес-процессов: https://www.omg.org/cgi-bin/doc?dtc/10-06-02
- Для Use Case-диаграммы принято рисовать ещё границу системы --- прямоугольник, внутри которого случаи использования, снаружи --- акторы. Чтобы визуально отделить то, что нам надо делать, от того, что нам делать не надо. Но вообще она good enough, её можно не править

2019-06-10 16:52 UTC, akhvorov commented
Первые три поправил вроде, а вот с четвертым проблемы. Вроде картинки посмотрел, но пока обнаружил только, что конечную чель бубликом надо рисовать. Предполгаю, что ремонт можно разнести на части, чтобы в одном месте за сборку кузова отвечали, в другом за покраску, но не уверен, что это то, что надо. Или дело в том, что оно выглядит некрасиво и стрелочки по диагонали идут вместо вертикали и горизонтали? Подозреваю, что не в этом, что что-то я запутался.

2019-06-16 21:01 UTC, yurii-litvinov requested changes
- А на IDEF0-диаграмме первого уровня загруженность конвейера не поправили, это всё ещё выглядт как внешнее управление
- Конечная цель рисуется бубликом, да. Помимо этого:
  - Условие, по которому происходит ветвление, пишется не внутри ромба, а снизу, или не пишется вовсе, а варианты указваются на стрелках, из него ведущих
  - То же с событием начала процесса --- это пустой белый круг, под которым можно написать условие начала
  - "Передать что-то-там", видимо, подразумевает посылку сообщения, тогда это рисуется как активность с конвертиком внутри и само сообщение пунктирной линией соединяет активность отправки с активностью, которая сообщение принимает. Но сообщения передаются только другим бизнес-процессам (то есть другим пулам), а тут у нас бизнес-процесс один, так что сообщения не нужны, а активность "передать план" по сути вообще не нужна, её роль играет сам поток исполнения
  - Бизнес-процесс должен быть целостным, то есть не должно быть блоков, кроме конечного, из которых не выходят стрелки
- И да, стрелки не очень, хоть это и не требование стандарта. Но лучше их сделать всё-таки горизонтально-вертикальными и обязательно не пересекающими фигуры

2019-06-18 16:57 UTC, akhvorov commented
- Про первый пункт не понял, вроде еще в тот раз убрал загруженность
- Тут поправил первый, второй и четвертый подпункт. Третий не очень понял(
- Поправил

2019-06-18 17:22 UTC, yurii-litvinov commented
Я про вот это:
![image](https://user-images.githubusercontent.com/706768/59705143-77dde280-9206-11e9-98d7-2151f3e38e7d.png)

По поводу "передать" я к тому, что блоки в BPMN --- это активности, то есть когда кто-то что-то реально делает. Если "передать план" -- это реально большая работа, то да, это активность. Если это просто сказать ребятам с производства, что вот вам план, работайте --- то этот блок лучше вообще не рисовать.

Но вообще, теперь это всё выглядит вполне адекватно, так что не виду причин просить Вас поправить. Зачтена.

2019-06-23 19:17 UTC, merged